### PR TITLE
Avoid a DeprecationWarning

### PR DESCRIPTION
**Pull request by hroncok**
DeprecationWarning: Flags not at the start of the expression '^(?u)[^\\W\\d][-\\w]*$'

Fixes https://github.com/asciidoc/asciidoc-py3/issues/13

Unicode regexes are default on Python 3:

https://docs.python.org/3/library/re.html#re.ASCII

### CODE REVIEW

**Comment by elextr** [comment]
LGBI, @MasterOdin any problems you see?

**Comment by MasterOdin** [comment]
Should probably also remove all of the instances of `(?u)` out of the various output configuration files (`docbook.conf`, `asciidoc.conf`, `xhtml11.conf`, etc.)

**Comment by hroncok** [comment]
Amended.

**Comment by MasterOdin** [comment]
LGTM

**Pull request merged**
